### PR TITLE
Add support for PBS v3.2.7

### PR DESCRIPTION
**Pull request by clansty**
This PR add support for PBS v3.2.7

Tested build on x86_64

The following changes has been made, the progress cost me >5 hours:

- Some of the existed patches shoudd be changed
- The `.cargo/config` file has been renamed to `.cargo/config.toml` so we should add new filename to `strip-cargo.bash`
- The test of `proxmox-perl-rs/pve-rs` not run, and has been removed by a new patch
- `proxmox-perl-rs/pve-rs` [adds dependences of libproxmox-rs-perl](https://git.proxmox.com/?p=proxmox-perl-rs.git;a=blobdiff;f=pve-rs/debian/control;h=ae5e4eb890ed6ae39b998f504d3e2ecea335db6d;hp=75de26e5c1933b055a53cc5c48c73d32d43ee5fa;hb=16c41f1a91e32ff189395e3bd8ef515850673422;hpb=86706cc049a7f9695dfd2a7886da8d635e99162b) to load `Proxmox::Lib::SslProbe` needed for the test. But this leads to circular dependency. It's safe to remove the dependency
- In package `proxmox-backup`, the Debian's cargo wrapper explains `debian/cargo_home/config` not found, and added a `-Zavoid-dev-deps` which is nightly feature to the real cargo, but did nothing good. So I replaced it with the real cargo
- Maybe replacing the Debian cargo wrapper changed the rust `target` dir from `target/$(DEB_HOST_RUST_TYPE)/release` to `target/release` so I manually added an arg to cargo to define `target` dir. Generation of docs and some tests depends on it

### CODE REVIEW

**Comment by clansty** [comment]
The built container unable to run and shows `Error: unable to start daemon - paths must not contain interior null bytes` without any backtrace. I think we need to debug the rust code

**Comment by clansty** [comment]
Solved!

image

**Comment by maximko** [comment]
please merge this one

**Review by ayufan — APPROVED** [review]
Awesome work. Let me validate everything and push new image.

**Comment by PPP01** [comment]
It would be so great, to have this new image!

**Pull request merged**
